spring.application.name=EduVerse
server.port=8087
spring.profiles.active=development

springdoc.api-docs.enabled=true
springdoc.swagger-ui.csrf.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger